
import { ArrowLeft } from 'lucide-react';

interface TermsPageProps {
  onBack: () => void;
}

export default function TermsPage({ onBack }: TermsPageProps) {
  return (
    <div className="flex-1 overflow-y-auto w-full bg-background relative animate-fade-in">
      <div className="absolute top-4 left-4 z-10 flex gap-2">
         <button onClick={onBack} className="p-2 border border-border rounded-lg bg-surface hover:bg-surface-hover transition-colors">
            <ArrowLeft className="w-5 h-5 text-muted-foreground" />
         </button>
      </div>
      
      <div className="max-w-3xl mx-auto px-6 py-20 min-h-[80vh]">
        <div className="mb-12 mt-8">
            <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-4 font-sans">
              Terms of Service
            </h1>
            <p className="text-muted-foreground">
              Last updated: May 4, 2026
            </p>
        </div>

        <div className="prose prose-neutral dark:prose-invert max-w-none">
            <p className="lead text-lg text-muted-foreground mb-8">
                Welcome to Impersio AI. By accessing or using our services, you agree to be bound by these Terms of Service.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4">1. Acceptance of Terms</h3>
            <p className="text-muted-foreground mb-6">
                By accessing or using the Impersio AI platform, you agree to comply with and be bound by these Terms. If you do not agree, please do not use the service.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4">2. Use of Service</h3>
            <p className="text-muted-foreground mb-6">
                You agree not to misuse the Impersio AI services. This includes not interfering with our services or trying to access them using a method other than the interface and the instructions that we provide.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4">3. Content and AI Generations</h3>
            <p className="text-muted-foreground mb-6">
                Our service heavily relies on artificial intelligence. While we strive for accuracy, the information provided by Impersio AI is generated algorithmically and may not always be pristine or perfect. You are responsible for how you use the output generated by our models.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4">4. Intellectual Property</h3>
            <p className="text-muted-foreground mb-6">
                Impersio AI, created and owned by Anubhav Sapkota, retains all rights, title, and interest in and to the platform, including all associated intellectual property rights.
            </p>
        </div>
      </div>
    </div>
  );
}
