import React, { useState, useRef } from 'react';
import { ChevronLeft, ChevronRight, Download, Maximize2, X, Image as ImageIcon, Upload } from 'lucide-react';
import { SlidesWidgetData } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import PptxGenJS from 'pptxgenjs';

interface SlidesWidgetProps {
  data: SlidesWidgetData;
}

export const SlidesWidget: React.FC<SlidesWidgetProps> = ({ data }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [userImages, setUserImages] = useState<Record<number, string>>({});
  const fileInputRef = useRef<HTMLInputElement>(null);

  const nextSlide = () => {
    setCurrentIndex((prev) => (prev + 1) % data.slides.length);
  };

  const prevSlide = () => {
    setCurrentIndex((prev) => (prev - 1 + data.slides.length) % data.slides.length);
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const reader = new FileReader();
      reader.onload = (ev) => {
        if (ev.target?.result) {
          setUserImages(prev => ({ ...prev, [currentIndex]: ev.target!.result as string }));
        }
      };
      reader.readAsDataURL(file);
    }
  };

  const triggerImageUpload = () => {
    fileInputRef.current?.click();
  };

  const downloadPresentation = async () => {
    const pres = new PptxGenJS();
    pres.layout = 'LAYOUT_16x9';

    // Professional White Theme
    const BG_COLOR = 'FFFFFF';
    const TEXT_COLOR = '333333';
    const TITLE_COLOR = '111111';
    const ACCENT_COLOR = '20b8cd'; // Keep brand accent

    // Helper to get image data (Base64 is safest for browser generation)
    const getImageDataForSlide = async (idx: number, url?: string) => {
        if (userImages[idx]) return userImages[idx]; // User uploaded (Data URL)
        if (!url) return null;
        if (url.startsWith('data:')) return url;

        try {
            // Try to fetch to avoid CORS in PPT viewer, but if CORS fails here, fallback to URL
            const response = await fetch(url);
            const blob = await response.blob();
            return await new Promise<string>((resolve) => {
                const reader = new FileReader();
                reader.onloadend = () => resolve(reader.result as string);
                reader.readAsDataURL(blob);
            });
        } catch (e) {
            return url; // Fallback to URL link
        }
    };

    // 1. Title Slide
    let slide = pres.addSlide();
    slide.background = { color: BG_COLOR }; 
    
    // Decorative Bar
    slide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.15, fill: ACCENT_COLOR });

    slide.addText(data.title, { 
        x: 0.5, y: 2.5, w: '90%', h: 1.5, 
        fontSize: 44, color: TITLE_COLOR, bold: true, align: 'center', fontFace: 'Arial' 
    });
    slide.addText('Generated by Impersio', { 
        x: 0.5, y: 4.2, w: '90%', h: 0.5, 
        fontSize: 14, color: '666666', align: 'center', fontFace: 'Arial' 
    });

    // 2. Content Slides
    for (let i = 0; i < data.slides.length; i++) {
        const s = data.slides[i];
        slide = pres.addSlide();
        slide.background = { color: BG_COLOR };
        
        // Slide Number
        slide.addText(`${i + 1}`, { x: 9.2, y: 5.1, w: 0.5, h: 0.3, fontSize: 10, color: '999999' });

        // Slide Title
        slide.addText(s.title, { 
            x: 0.5, y: 0.4, w: '90%', h: 0.8, 
            fontSize: 32, color: TITLE_COLOR, bold: true, fontFace: 'Arial' 
        });

        // Separator
        slide.addShape(pres.ShapeType.line, { x: 0.5, y: 1.2, w: '90%', h: 0, line: { color: ACCENT_COLOR, width: 2 } });

        const hasChart = !!s.chart;
        const imgData = await getImageDataForSlide(i, s.image);
        const hasImage = !!imgData;
        
        let textWidth = '90%';
        let contentX = 0.5;

        // Layout Logic
        if (hasChart || hasImage) {
            textWidth = '50%';
        }

        // Bullet Points
        const bullets = s.content.map(text => ({ 
            text, 
            options: { 
                fontSize: 18, 
                color: TEXT_COLOR, 
                breakLine: true, 
                bullet: { type: 'bullet', code: '2022' }, 
                paraSpaceBefore: 12,
                lineSpacing: 28
            } 
        }));
        
        slide.addText(bullets, { 
            x: contentX, y: 1.5, w: textWidth, h: 3.5, 
            align: 'left', valign: 'top', fontFace: 'Arial' 
        });

        // Add Chart
        if (hasChart && s.chart) {
             const chartData = [
                {
                    name: s.chart.title || "Data",
                    labels: s.chart.data.map(d => d.label),
                    values: s.chart.data.map(d => d.value)
                }
             ];
             slide.addChart(pres.ChartType.bar, chartData, { 
                 x: 5.8, y: 1.5, w: 3.8, h: 3, 
                 chartColors: [ACCENT_COLOR],
                 valAxisLabelColor: '666666',
                 catAxisLabelColor: '666666',
                 showTitle: true,
                 title: s.chart.title || "Data Analysis"
             });
        }

        // Add Image
        if (hasImage && imgData && !hasChart) {
            try {
                slide.addImage({ 
                    data: imgData.startsWith('data:') ? imgData : undefined,
                    path: !imgData.startsWith('data:') ? imgData : undefined,
                    x: 5.8, y: 1.5, w: 3.8, h: 3,
                    sizing: { type: 'contain', w: 3.8, h: 3 }
                });
            } catch (e) {
                console.error("Failed to add image to PPT", e);
            }
        }
    }

    pres.writeFile({ fileName: `${data.title.replace(/[^a-zA-Z0-9]/g, '_')}.pptx` });
  };

  const currentSlide = data.slides[currentIndex];
  const activeImage = userImages[currentIndex] || currentSlide.image;

  const RenderContent = () => (
    <div key={currentIndex} className="absolute inset-0 p-6 md:p-8 flex flex-col bg-surface animate-in fade-in duration-300">
        <div className="flex justify-between items-start mb-6">
            <h2 className="text-2xl md:text-3xl font-bold text-scira-accent leading-tight truncate flex-1 pr-4">
                {currentSlide.title}
            </h2>
             {/* Slide specific actions */}
             <div className="flex gap-2">
                 <button 
                   onClick={triggerImageUpload}
                   className="p-2 rounded-lg bg-surface-hover hover:bg-border text-muted hover:text-primary transition-colors"
                   title="Add/Replace Image"
                 >
                   <ImageIcon className="w-4 h-4" />
                   <input 
                     type="file" 
                     ref={fileInputRef} 
                     onChange={handleImageUpload} 
                     className="hidden" 
                     accept="image/*"
                   />
                 </button>
             </div>
        </div>
        
        <div className="flex-1 flex gap-6 min-h-0">
            {/* Text Content */}
            <div className={`flex-1 overflow-y-auto ${currentSlide.chart || activeImage ? 'w-full md:w-1/2' : 'w-full'} pr-2`}>
                <ul className="space-y-4">
                    {currentSlide.content.map((point, idx) => (
                        <li key={idx} className="flex items-start gap-3 text-lg text-primary/90">
                            <span className="mt-2.5 w-1.5 h-1.5 rounded-full bg-scira-accent shrink-0" />
                            <span className="leading-relaxed">{point}</span>
                        </li>
                    ))}
                </ul>
            </div>

            {/* Right Side: Chart or Image */}
            {(currentSlide.chart || activeImage) && (
                <div className="hidden md:flex w-1/2 h-full items-center justify-center">
                    {currentSlide.chart ? (
                        <div className="w-full h-full max-h-[300px] bg-background/50 rounded-xl p-4 border border-border">
                            <h3 className="text-sm font-semibold text-muted mb-4 uppercase tracking-wider">{currentSlide.chart.title || "Data Analysis"}</h3>
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={currentSlide.chart.data}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                                    <XAxis 
                                        dataKey="label" 
                                        stroke="#71717a" 
                                        tick={{fill: '#71717a', fontSize: 12}} 
                                        tickLine={false} 
                                        axisLine={false}
                                        interval={0}
                                    />
                                    <YAxis 
                                        stroke="#71717a" 
                                        tick={{fill: '#71717a', fontSize: 12}} 
                                        tickLine={false} 
                                        axisLine={false} 
                                    />
                                    <Tooltip 
                                        contentStyle={{backgroundColor: '#18181b', borderColor: '#27272a', color: '#fff'}}
                                        itemStyle={{color: '#fff'}}
                                        cursor={{fill: '#27272a', opacity: 0.5}}
                                    />
                                    <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                                        {currentSlide.chart.data.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={index % 2 === 0 ? '#20b8cd' : '#3f2510'} />
                                        ))}
                                    </Bar>
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    ) : activeImage ? (
                        <div className="w-full h-full max-h-[300px] rounded-xl overflow-hidden border border-border relative group/img">
                            <img 
                                src={activeImage} 
                                alt={currentSlide.title} 
                                className="w-full h-full object-cover"
                            />
                            {/* Hover overlay to change image */}
                            <div className="absolute inset-0 bg-black/40 opacity-0 group-hover/img:opacity-100 transition-opacity flex items-center justify-center">
                                <button onClick={triggerImageUpload} className="px-4 py-2 bg-white/10 backdrop-blur-md rounded-full text-white font-medium flex items-center gap-2 hover:bg-white/20">
                                    <Upload className="w-4 h-4" /> Change
                                </button>
                            </div>
                        </div>
                    ) : null}
                </div>
            )}
        </div>
    </div>
  );

  if (isFullscreen) {
    return (
        <div className="fixed inset-0 z-50 bg-background flex flex-col p-6 animate-in zoom-in-95 duration-200">
             <div className="absolute top-4 right-4 flex gap-4 z-10">
                 <button onClick={downloadPresentation} className="p-2 rounded-full bg-surface hover:bg-surface-hover text-primary transition-colors flex items-center gap-2 px-4 shadow-lg border border-border">
                     <Download className="w-5 h-5" />
                     <span className="text-sm font-medium">Download PPTX</span>
                 </button>
                 <button onClick={() => setIsFullscreen(false)} className="p-2 rounded-full bg-surface hover:bg-surface-hover text-primary transition-colors shadow-lg border border-border">
                     <X className="w-5 h-5" />
                 </button>
             </div>
             
             <div className="flex-1 flex items-center justify-center max-w-7xl mx-auto w-full">
                 <div className="w-full aspect-[16/9] bg-surface border border-border rounded-2xl relative shadow-2xl overflow-hidden">
                    <RenderContent />
                    
                     {/* Controls */}
                    <div className="absolute inset-x-0 top-1/2 -translate-y-1/2 flex justify-between px-4 pointer-events-none">
                        <button onClick={prevSlide} className="pointer-events-auto p-4 rounded-full bg-black/50 hover:bg-black/70 text-white backdrop-blur-sm transition-all hover:scale-105 active:scale-95">
                            <ChevronLeft className="w-8 h-8" />
                        </button>
                        <button onClick={nextSlide} className="pointer-events-auto p-4 rounded-full bg-black/50 hover:bg-black/70 text-white backdrop-blur-sm transition-all hover:scale-105 active:scale-95">
                            <ChevronRight className="w-8 h-8" />
                        </button>
                    </div>
                    
                    <div className="absolute bottom-6 right-8 text-sm text-muted font-medium bg-background/90 px-3 py-1 rounded-full border border-border">
                        {currentIndex + 1} / {data.slides.length}
                    </div>
                 </div>
             </div>
        </div>
    );
  }

  return (
    <div className="w-full max-w-3xl mx-auto mb-8 bg-surface border border-border rounded-2xl overflow-hidden shadow-lg transition-all hover:shadow-xl group">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-surface-hover/30">
         <div className="flex items-center gap-2">
             <div className="w-3 h-3 rounded-full bg-red-500/80" />
             <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
             <div className="w-3 h-3 rounded-full bg-green-500/80" />
         </div>
         <div className="text-xs font-semibold text-muted uppercase tracking-wider truncate max-w-[200px]">{data.title}</div>
         <div className="flex items-center gap-1">
             <button onClick={downloadPresentation} className="p-1.5 rounded-lg text-muted hover:text-primary hover:bg-background/50 transition-colors flex items-center gap-1.5 pr-2.5" title="Download PPTX">
                 <Download className="w-4 h-4" />
                 <span className="text-xs font-medium">PPTX</span>
             </button>
             <button onClick={() => setIsFullscreen(true)} className="p-1.5 rounded-lg text-muted hover:text-primary hover:bg-background/50 transition-colors" title="Fullscreen">
                 <Maximize2 className="w-4 h-4" />
             </button>
         </div>
      </div>

      {/* Slide Preview */}
      <div className="aspect-[16/9] bg-background relative overflow-hidden group/preview">
          <RenderContent />
          
          {/* Controls Overlay */}
          <div className="absolute inset-0 flex items-center justify-between px-2 opacity-0 group-hover/preview:opacity-100 transition-opacity pointer-events-none">
              <button onClick={prevSlide} className="pointer-events-auto p-2 rounded-full bg-black/20 hover:bg-black/40 text-white backdrop-blur-sm transition-all hover:scale-110">
                  <ChevronLeft className="w-5 h-5" />
              </button>
              <button onClick={nextSlide} className="pointer-events-auto p-2 rounded-full bg-black/20 hover:bg-black/40 text-white backdrop-blur-sm transition-all hover:scale-110">
                  <ChevronRight className="w-5 h-5" />
              </button>
          </div>
          
          <div className="absolute bottom-3 right-4 text-[10px] text-muted font-medium bg-background/80 px-2 py-0.5 rounded-full border border-border">
              {currentIndex + 1} / {data.slides.length}
          </div>
      </div>
    </div>
  );
};